### ISSUE TITLE
New sheet created each time for data writting

### ISSUE THREAD

**Issue by Saurabh06** [Zertz/xlsx-json2ws#1]
Not write json data into existing sheet present at that location instead it creates new one and write data into that sheet.

**Comment by Zertz** [comment]
Would you mind clarifying the issue you're having? Some code and the expected behavior would help.

**Comment by Saurabh06** [comment]
@Zertz , i want to use old `workbook.xlsx` present in some other location and try to paste it in specified location and want to add data into old Sheet1 and Sheet2 data sheet present in that workbook

xlsx.writeFile({
  SheetNames: ['Sheet1', 'Sheet2'],
  Sheets: {
    Sheet1: json2xlsx(data),
    Sheet2: json2xlsx(data)
  }
}, 'workbook.xlsx')

**Comment by Zertz** [comment]
All this does is convert `JSON` to `xlsx`, as for appending to an existing file, I'm afraid I can't help you there. Try having a look at the [xlsx module documentation](https://www.npmjs.com/package/xlsx).
